kind: pipeline
type: docker
name: default

workspace:
  path: golang

steps:
  - name: golang_test
    image: golang:latest
    commands:
      - pwd
      - ls -al
      - cd golang
      - go vet
      - go test -v -cover
  - name: golang_build
    image: golang:latest
    commands:
      - cd golang
      - go build
